name: bubbly
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  bubbly_camera:
    path: "CameraPlugin/camera"
  retrytech_plugin:
    git:
      url: https://gitlab.com/jeelkhokhariya59/retrytech_plugin.git
      ref: master

  cupertino_icons: ^1.0.8
  flutter_cache_manager: ^3.4.1
  camera: ^0.11.1

  #_______________ In App Purchase ___________________#
  in_app_purchase: ^3.2.1

  #_______________ Firebase,Notification,Ads ___________________#
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1
  google_mobile_ads: ^6.0.0

  #_______________ Sign in ___________________#
  google_sign_in: ^6.2.2

  #_______________ Functionality ___________________#

  http: ^1.3.0
  shimmer: ^3.0.0
  qr_flutter: ^4.1.0
  qr_code_scanner_plus: ^2.0.10+1
  url_launcher: ^6.3.1
  intl: ^0.20.2
  image_gallery_saver_plus: ^4.0.1
  shared_preferences: ^2.5.3
  webview_flutter: ^4.13.0
  flutter_branch_sdk: ^8.4.0
  share_plus: ^10.1.4
  audioplayers: ^6.3.0
  audioplayers_darwin: ^6.1.1
  video_player: ^2.9.3

  #----------------- UI -----------------#
  screenshot: ^3.0.0
  fluttertoast: ^8.2.12
  device_info_plus: 
  visibility_detector: ^0.4.0+2
  wakelock_plus: ^1.3.2
  flutter_staggered_grid_view: ^0.7.0
  detectable_text_field: ^3.0.2
  bouncing_widget: ^2.0.0


  #----------------- Image,Files,Permission -----------------#

  path_provider: ^2.1.5
  image_picker: ^1.1.2
  video_compress: ^3.1.4
  permission_handler: ^11.4.0
  collection:
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
  logger: ^2.5.0
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  path:

  #----------------- Live Stream -----------------#
  agora_rtc_engine: ^6.5.0

  #----------------- State Management -----------------#
  stacked: ^3.4.4
  provider: ^6.1.2
  get: ^4.7.2
  connectivity_plus: ^6.1.4
  tiktok_double_tap_like: ^1.0.5+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^9.1.9
  build_runner: ^2.4.15

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - icons/

  fonts:
    - family: SfUiBold
      fonts:
        - asset: font/SFUIDisplayBold.otf
    - family: SfUiLight
      fonts:
        - asset: font/SFUIDisplayLight.otf
    - family: SfUiMedium
      fonts:
        - asset: font/SFUIDisplayMedium.otf
    - family: SfUiHeavy
      fonts:
        - asset: font/SFUIDisplayHeavy.otf
    - family: SfUiRegular
      fonts:
        - asset: font/SFUIDisplayRegular.otf
    - family: SfUiSemiBold
      fonts:
        - asset: font/SFUIDisplaySemibold.otf

